[package]
name = "retest"
version = "0.2.2"
authors = ["Stephen Coakley <me@stephencoakley.com>"]
license = "Apache-2.0"
readme = "README.md"

[dependencies]
getopts = "0.2"
regex = "1.0"
term = "0.5"
