[package]
name = "retest"
version = "0.2.1"
authors = ["coderstephen <me@stephencoakley.com>"]
license = "Apache-2.0"
readme = "README.md"

[dependencies]
getopts = "0.2"
regex = "0.1.8"
term = "0.2"
