name: teto
on:
  issue_comment:
    types: [created]

jobs:
  teto:
    runs-on: ubuntu-latest
    steps:
      - uses: sagebind/teto-bot@master
        with:
          token: ${{ secrets.TETO_PAT }}
